### ISSUE TITLE
How to prepare expression matrix for NMF

### ISSUE THREAD

**Issue by qinghezeng** [tiroshlab/Spatial_Glioma#1]
Hi,
Thanks for providing the nice code! I just noticed that the part of code to prepare the expression matrix for NMF is not included in the script Module1_MP.R. It would be great if you can check and upload it. Thank you very much!
Best,
Qinghe

**Comment by alissacg** [comment]
Hi Qinghe,
We can add the code to prepare the expression matrix for NMF but in the mean time, I can tell you that the input is the log-transformed centered expression matrix with negative values transformed to zero. Hope this helps!

**Comment by qinghezeng** [comment]
Hi Alissacg,
Thank you for your prompt reply! I also notice that the dimension of the NMF input file is different from the Seurat object (after the QC). What criteria did you used to filter the spots and genes? Thank you very much in advance!

**Comment by alissacg** [comment]
We filtered spots with under 1000 counts or with 20% or more mitochondrial genes. We filtered genes with mean expression values less than or equal to 0.4 (following normalization and log transformation).

**Comment by qinghezeng** [comment]
Thank you for your prompt reply! However, with your code for spot filtering as follows

```
complexity_filter <- 1000
mitochondrial_filter <- 20

exp_obj <- subset(unfilt_obj, subset = nCount_Spatial > complexity_filter) # filter out spots with less than #complexity_filter UMIs
exp_obj[["percent.mt"]] <- PercentageFeatureSet(exp_obj, pattern = "^MT-") # filter spots with high percent (mitochondrial_filter) mitochondrial genes
exp_obj <- subset(exp_obj, subset = percent.mt<mitochondrial_filter)
```

It appears that there is a discrepancy in the spot numbers between the provided NMF input and the data after filtering. For instance, in your sample MGH258, there are 2212 spots retained (matching the column number in the _general/exp_mats_GBM_ folder), yet the corresponding NMF input matrix (in _MP/NMF/NMF_mats_GBM_) contains only 2201 columns. Could you please clarify what might be causing this difference?

Additionally, the NMF (version 0.27) computation is proving to be very computationally intensive, taking approximately one day per rank per sample on our workstation equipped with 192GB RAM. Could you share the specifications of the hardware you used and any recommendations for speeding up this process? Thank you so much!!!

**Comment by alissacg** [comment]
The code for generating the NMF input matrices is now added to module 1. Yes, unfortunately the NMF is extremely computationally heavy to run. We don't run it locally but on our server with each sample running in parallel.
