### ISSUE TITLE
Regarding module 5

### ISSUE THREAD

**Issue by autumnfe79** [tiroshlab/Spatial_Glioma#2]
I have two questions regarding thid module 5.

1. In the middle of code of module 5, you used infercna::cnaPlot function. But, this function was deprecated a long time ago. Perhaps, do you share source code of this function?

2. Also, in the begening of the code, you loaded 'samples_regeions.txt'. It is required for merge_cna_md_fx. What kinds of information should it contain? Withoug this file, I coun't peforem merge_cna_md_fx.

**Comment by noam-g** [comment]
1. we currently don't use a formal substitute. 
2. this should include a table with the columns: 
a. cna_samples_name: either the original name of the samples or a merged name for the merged sample	
b. sample: the original names of the samples 	
c. region: either "tumor" or specified tumor region
