### ISSUE TITLE
Your Iinput.zip could not be download！

### ISSUE THREAD

**Issue by wang999-sdu** [tiroshlab/Spatial_Glioma#3]
Hi~
Thank you for sharing the valuable code, it is very helpful to us. However, we found that your input.zip file could not be downloaded, could you re-upload it or share it in a different way? This will be of great help to us, and we very much look forward to learning from your work. Thank you very much!

**Comment by noam-g** [comment]
We've successfully downloaded it from different locations. Could it be a different issue?
