### ISSUE TITLE
How do you define the biological character of MPs

### ISSUE THREAD

**Issue by yeswzc** [tiroshlab/Spatial_Glioma#4]
Hi,

I have a question not related to the code but to the paper. I wonder how you annotate these programs.

After you defined the molecular programs, how do you name the programs by their genes? By some enrichment analysis like gene ontology enrichment or manual annotation?

Thank you!
Zee

**Comment by alissacg** [comment]
Hi Zee, for the majority of metaprograms we name them based on enrichment analysis (in the paper, see Fig. 2D and S2C for the most enriched signatures per metaprogram). We calculated enrichment values by hypergeometric test. The programs of the core malignant states (MES, MES-Hyp, NPC, OPC, AC) overlap very highly with their single-cell counterpart states that were defined in Neftel et al. (2019).  Two of the malignant states that we defined from the spatial data that were not described previously (Chromatin Reg. and Proliferative Metabolism) we named by manual annotation of the genes.
