### ISSUE TITLE
How to prepare input for module 4 (Summary_tables folder)

### ISSUE THREAD

**Issue by qinghezeng** [tiroshlab/Spatial_Glioma#6]
Hi,

Thank you once again for the excellent code! 

I wonder how to generate the files in the Summary_tables folder starting from module 3, which are used as input for module 4. It would be great if you could upload the transition code. Thank you very much!!

Best,
Qinghe

**Comment by noam-g** [comment]
This is described in the methods section of the paper. We might upload it in future versions as we are currently working on a more user-friendly version.
